### PR TITLE
Robust noise model post

### PR DESCRIPTION
**Pull request by varunagrawal**
It took a while to get the Katex configuration up and running because the theme used by the site does not have an explicit head or footer layouts. I had to hack it to get it to work well, but it is usable in general. We may have to clean this up in the future.

### CODE REVIEW

**Comment by mikesheffler** [comment]
I can't (I don't think) see the rendered version of the blog post, so I won't comment on that, but ...

> What 2D images do we frequently see rotated and translated? Something that can maybe be displayed side by side. Or even in same image: like two identical magazines or fliers or photos, scattered on a desk (and viewed from above).

When people are test driving feature detectors and learning about homographies, I think the [Graffiti](http://www.robots.ox.ac.uk/~vgg/data/data-aff.html) dataset is (are) some images that I've seen rotated, scaled, etc.  more than any other.

If you want repeated instances of similar objects in the _same_ view, you can use shopping pictures, like [these crayons](https://www.alamy.com/stock-photo-north-miami-beach-florida-wal-mart-walmart-school-supplies-crayola-141937469.html)  or [these crayons](https://www.pilotonline.com/news/columns/article_7a7a7fee-a198-11e8-b2d8-2b16951d7362.html). Can't get enough crayons. 😁

**Comment by varunagrawal** [comment]
1. Sure thing. I can tease the final result in the introduction and then lead into the parameter estimation tutorial.
2. I've seen some images like this. Let me try with those and update the post.
3. I don't understand which part this is referring to. Is this the derivation part, because that was meant to be theoretical...
4. I do write that. I mention how RANSAC is a common tool but we need something better. I tried to use topic sentences here too that's why you see the 2nd paragraph immediately mention the robust noise models.

**Comment by dellaert** [comment]
3. Are you not talking about conic fitting in theoretical part? Why? Why can't we just use SE(2) ?
4. Second paragraph is "burying the lede". I suggest topics for para 1 and 2:
"Robust error models are amazingly powerful."
"Robust error models can even obviate the need for more complicated algorithms like RANSAC."

**Comment by varunagrawal** [comment]
I was hoping to pick up the derivations from Zhengyou Zhang's paper and not reinvent the wheel. That way, when the reader reads the paper for more details, the transition is straightforward.

**Comment by varunagrawal** [comment]
@mikesheffler thanks for the crayons image. I really liked the 2nd one so went ahead and used that.

@dellaert 

1. I added some images in the Intro demonstrating the image recovery using the different techniques. This seemed like a cool, visual way of motivating our post.
2. I used the crayons image recommended by Mike.
3. I can improve this to use `SE(2)`? I am not sure how hard/time consuming the derivations might be...
4. Thank you for the suggestions. I now start off with the Robust Noise Models and their utility.

**Comment by varunagrawal** [comment]
@mikesheffler if you want to see the rendered version, I guess you'll have to run jekyll locally? I don't know what your comfort level with Ruby tooling is.

**Comment by mikesheffler** [comment]
I'll have to give it a whirl ...

**Comment by dellaert** [comment]
Comments:
- x,theta -> theta;x
- book image
- revise rest (conic)

**Comment by dellaert** [comment]
I think you’re still making a reference to the crayon images. Are you still using those?

**Comment by varunagrawal** [comment]
Yup I am working on using the provided image. This PR is not ready yet. :slightly_smiling_face:

**Comment by varunagrawal** [comment]
@dellaert I've added your provided image and rewrote the post to make that as the primary example.
I've also retained the crayons example as an additional example because I think the results are pretty impressive and make a strong case for the post.

**Comment by dellaert** [comment]
Is it ready to go now?

**Comment by varunagrawal** [comment]
Yes it should be. If I have your approval, this is ready to be published.

**Pull request merged**
