### PR TITLE
WIP of Release blog

### PR DESCRIPTION
**Pull request by ProfFan**
@dellaert In order to preview please clone locally and run `bundle exec jekyll serve`, the 3D figures should render nicely.

### CODE REVIEW

**Comment by ProfFan** [comment]
> Hey, I did some editing of the text, but I still have some comments:
> 
> * in the figures, what is "Default"? I know you mean the "old" default, but this post is about a new Default, so it's confusing ! Replace "Default with Cayley?"

Changed annotations to Cayley instead.

> * _still_ one of the plots has dots and the other ones don't. And, the left and right don't agree on the markers. Can we fix that?

Done

> * the plotly figures are great, but can you put them in separate files to be included?

They are already in separate files (the export is a gigantic html which I already separated to a JSON) but I have improved a bit more.

> * I think the plotly should camera Cayley with the new default, full exponential map - the titles suggest otherwise

Changed.

> * The list of fixes and features at the end is missing

Added those I think are rather important.

**Comment by ProfFan** [comment]
> Looks great! Two small issues with plotly:
> 
> * the error numbers overlap in my browser
>   image

Fixed

> * when you zoom in, the traces become very small and almost useless.

Hmm, that is kinda intended (I tried a lot of methods to make the points zoom, none work, and there are open discussions on plotly forum)...

**Comment by dellaert** [comment]
OK, well, I think we're ready to merge develop into release/4.0.3 and merge this blog post, *after* PR #416 lands. Is just some docs cleanup so should be easy to review, merge. I will let *you* handle the release process.

**Comment by ProfFan** [comment]
@dellaert I'll merge this and do the do the release?

**Pull request merged**
