### PR TITLE
Fix various formatting issues in Tutorial

### PR DESCRIPTION
**Pull request by acxz**
Went through and fixed some formatting issues in the tutorial. Still one more equation that contains the Squared Mahalanobis remains to be formatted. (Couldn't get subscripts to work instead the Mahalanobis term)

### CODE REVIEW

**Comment by dellaert** [comment]
Thanks !!!

**Comment by acxz** [comment]
Always a pleasure!

**Comment by dellaert** [comment]
@acxz hey Akash, I know this is been a long time, but did you make those changes directly on the HTML or you fix the lyx document in GTSAM? I have some math to correct, but I don't relish fixing the html directly and having it out of date with GTSAM.

**Comment by acxz** [comment]
Hello Professor, hope you are doing well!

I believe I changed the HTML directly so that there would be as small a diff as possible. In fact, I don't think I knew about the lyx document when I made these changes.

Yeah fixing the html is p rough.

If I were to perform these changes now, my recommendation would be to:
1. Edit lyx document directly
2. Export lyx document to html file
3. Commit this html file to have a commit with just the lyx->html conversion (easier to diff off of)
4. Render website locally and edit the html directly as needed.

Since there are prob 2 branches of this document (html ver here and lyx in the main repo) you may want to convert this html doc to lyx file first. (This might result in larger diffs in the lyx doc) 
Or it might be much easier to just apply the changes I made in this html doc manually in lyx directly.

**Pull request merged**
