### PR TITLE
fix margins and blank lines

### PR DESCRIPTION
**Pull request by acxz**
Seems like I added an extra </div> which has messed up the margins on the website.

### CODE REVIEW

**Comment by dellaert** [comment]
Let me merge and check...

**Comment by acxz** [comment]
Is there a way to locally generate the website with the CSS? I have only been able to look at the html locally?

**Comment by dellaert** [comment]
> Is there a way to locally generate the website with the CSS? I have only been able to look at the html locally?

Yes: https://help.github.com/en/github/working-with-github-pages/testing-your-github-pages-site-locally-with-jekyll

**Comment by dellaert** [comment]
Seems not quite fixed yet :-) Hopefully above link helps preview...

**Comment by acxz** [comment]
Thank you so much! Yeah now I can ensure it works well with the styling. I'll get back later today and get a proper fix out.

**Pull request merged**
